== Refleksjoner rundt robusthet, skalerbarhet og vedlikeholdbarhet
Siden vi brukte V-modellen og delte prosjektet opp i mindre moduler, som interagerer på lite komplekse måter, er det enkelt å legge til ny funksjonalitet eller endre gamel funksjonalitet. Man må bare finne ut hvilken modul endringen hører inn under, og så lenge brukergrensesnittet til modulen er uforandret vil prosjektet fungere. Vi har dessuten forøskt å ha en systematisk konvensjon på navngivning av variabler, med beskrivende navn, slik at det i etterkant skal være enkelt å sette seg inn i hva koden gjør. 

Det er derimot noen problemer med koden med hensyn på vedlikeholdbarhet. Det viktigste punktet er at vi ikke har skrevet noen dokumentasjon. For øyeblikket er det relativt tydelig for oss hva de ulike modulene gjør, men det er ikke skrevet ned, så andre personer, eller en senere versjon av oss selv, vil ha større problemer med å sette seg inn i koden, enn om vi hadde skrevet dokumentasjon.

Det andre problemet er at vi ikke bare gjorde fornuftige valg da vi valgte hva de ulike modulene skulle ha ansvar for. Dette har resultert i en del redundant kode, spesielt i output-modulen. Den sørger for at døren ikke er åpen i fart, at heisen ikke kjører utenfor etasje 1-4 osv. Dette sørger derimot allerede queue- og controll-modulen for. Output-modulen har altså veldig mange linjer med unødvendig kode, som gjør koden vanskligere å forstå enn nødvendig. Dette fører dessuten til at det er flere ulike steder i koden man kan ha problemer med åpning av dør og lignende. Dette bryter med prinssippet vårt om at modulene skal ha tydelig fordelte ansvar, slik at feil enkelt kan spores til riktig modul. 

Et annet problem med output-modulen er at den er skrevet for å kommunisere minst mulig med heisen, den vil for eksmepel aldri forsøke å slå på lys som allerede er på. Hensikten var å unngå at programflyten skulle stoppe unødvendig lenge i output-modulen, slik at systemet for eksmpel ikke rakk å registrere at heisen paserte forbi en etaje. Etter å ha snakket med andre grupper virker det derimot ikke som dette er en bug de har problemer med. Systmet vårt med å sende færrest mulig forespørsler til heisen bidrar altså til å gjør output-modulen mer komplisert, uten å løse et reelt problem. 

Et siste problem med hensyn på vedlikeholdbarhet er som kommentert tidligere at queue-modulen ikke er implementert som en tilstandsmaskin, dette gjør den mer uoversiktelig enn den trenger å være.